# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Nom de la boutique')),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude pour géolocalisation', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude pour géolocalisation', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil boutique',
                'verbose_name_plural': 'Profils boutiques',
                'db_table': 'boutique_profile',
                'indexes': [models.Index(fields=['city'], name='boutique_pr_city_4dcc43_idx')],
            },
        ),
    ]
