# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant brut')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux commission (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant commission')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant net transitaire')),
                ('release_status', models.CharField(choices=[('locked', 'Bloqué'), ('released', 'Libéré')], default='locked', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_transaction', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transaction séquestre',
                'verbose_name_plural': 'Transactions séquestre',
                'db_table': 'escrow_transaction',
                'indexes': [models.Index(fields=['order'], name='escrow_tran_order_i_83247d_idx'), models.Index(fields=['release_status'], name='escrow_tran_release_8d8b05_idx')],
            },
        ),
    ]
