# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitaireProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé')], default='active', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transitaire_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil transitaire',
                'verbose_name_plural': 'Profils transitaires',
                'db_table': 'transitaire_profile',
                'indexes': [models.Index(fields=['status'], name='transitaire_status_63ff4f_idx')],
            },
        ),
    ]
