# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('value_type', models.CharField(choices=[('str', 'Chaîne'), ('int', 'Entier'), ('decimal', 'Décimal'), ('bool', 'Booléen')], default='str', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'db_table': 'admin_site_systemsetting',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID objet')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'admin_site_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='admin_site__user_id_8fbf6d_idx'), models.Index(fields=['action'], name='admin_site__action_f23e70_idx'), models.Index(fields=['created_at'], name='admin_site__created_81e629_idx')],
            },
        ),
    ]
